Update CamHack

diff --git a/CamHack b/CamHack
--- a/CamHack
+++ b/CamHack
@@ -238,6 +238,11 @@ if ! [ `command -v proot` ]; then
     echo -e "${error}Proot can't be installed!\007\n"
     exit 1
 fi
+fi
+if ! [ `command -v php` ]; then
+    echo -e "${error}PHP cannot be installed!\007\n"
+    
+fi
 if ! [ `command -v curl` ]; then
     echo -e "${error}Curl cannot be installed!\007\n"
     exit 1
